### ISSUE TITLE
Remove bootstrap dependency

### ISSUE THREAD

**Issue by naterpotatoers** [libhal/web-serial#5]
Want to make web app look really professional. 
Might be able to achieve current results with less code/bloat. 
Still floating the idea but I think there are certain things that we definitely don't need bootstrap for and complicates the html/styling logic

**Comment by kammce** [comment]
Bootstrap was used back when this was made to make the site look professional and simple. It made styling really simple. If we can achieve this and remove bootstrap without too much additional code to manage, that would be great. But if it looks like we are reimplementing bootstrap then we'd have to pass on the PR. 

Given how many new CSS style attributes have been added in the past few years since I started this project, I'm certain most of this can be achieved without bootstrap.
